user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }

admin:
    path:   /admin
    defaults: { _controller: UserBundle:Admin:index}
AddClient:
    path:   /addClient
    defaults: { _controller: UserBundle:Client:addclient}
